# Generated by Django 6.0.3 on 2026-03-31 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empl", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование задачи",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        help_text="Введите срок исполнения",
                        null=True,
                        verbose_name="Срок исполнения",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("start", "start"), ("finish", "finish")],
                        default="start",
                        help_text="Введите статус",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "empl",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите исполнителя",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="empl.empl",
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите родительскую задачу",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other",
                        to="task_tracker.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
